import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { TopNavigation } from "@/components/organisms/navigation/TopNavigation";
import { cn } from "@/lib/utils";
import { AuthProvider } from "@/providers/AuthProvider";
import { ThemeProvider } from "@/providers/ThemeProviders";
import { ToasterProvider } from "@/providers/ToasterProvider";
import "./globals.css";

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<AuthProvider>
						<ToasterProvider>{children}</ToasterProvider>
					</AuthProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
